### ISSUE TITLE
eth.call fails with ‘Invalid Signature’

### ISSUE THREAD

**Issue by Recmo** [MetaMask/provider-engine#114]
I can send ordinary transactions, deploy contracts. I can not call functions on contracts or use `eth.call` or `eth.estimateGas`. If I try, I get the following stacktrace:

```
Error: Invalid Signature
    at FakeTransaction.getSenderPublicKey (dapp.js:43528)
    at FakeTransaction.getSenderAddress (dapp.js:43517)
    at populateCache (dapp.js:47251)
    at dapp.js:7501
    at replenish (dapp.js:4697)
    at dapp.js:4701
    at eachOfLimit (dapp.js:4728)
    at dapp.js:4733
    at _parallel (dapp.js:7500)
    at Object.series (dapp.js:8340) undefined
```

My set-up is the one from README.md, with the `HookedWalletSubprovider` callbacks implemented.

**Comment by LogvinovLeon** [comment]
It's probably because `web3.eth.defaultAccount` is not set.
The transaction would be executed in a client-side VM but it still needs to know who is the sender.
`web3.eth.getCoinbase((error, account) => {web3.eth.defaultAccount = account})` would solve the problem.
Or just assig anything to web3.eth.defaultAccount if you want other behaviour.

**Comment by sertony** [comment]
@Recmo have you managed to solve the problem? I am facing the same issue.
@LogvinovLeon 's solution is not working.

**Comment by davidqhr** [comment]
@LogvinovLeon Thank you! `web3.eth.defaultAccount` should be set when using the `VMSubprovider`. I think this should be metioned in the README.

**Comment by kumavis** [comment]
this was fixed by adding a default `from`

**Comment by kumavis** [comment]
also fixing upstream https://github.com/ethereumjs/ethereumjs-tx/pull/94
