### ISSUE TITLE
Cache - broken transaction caches

### ISSUE THREAD

**Issue by kumavis** [MetaMask/provider-engine#14]
Certain caches currently marked 'perma cache' need a lower caching level.
For example `eth_getTransactionByHash` has a block reference and will return with (incomplete information) while still pending. Once its mined into a block the block reference is added but we've already cached the result. Also note that the block reference could change at any time due to forks.

**Comment by tcoulter** [comment]
Thinking about this. Is there any way to write good tests for this? My first reaction is to add a "pause" feature into `ethereumjs-testrpc` which will pause transaction processing and return pending results until processing is started back up again (this implies that we'd use `ethereumjs-testrpc`'s as a provider for these tests).

**Comment by kumavis** [comment]
very easy to test, just return a json blob for the tx without a block.
doesn't require a vm or anything approximating a full node.

The result looks like this when it does not yet have a block:
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "hash": "0x8ea908ca2d8bb2b4b45c7311def60c4e4c735a7c6e851f1ed75e5d4a64330eb2",
        "nonce": "0xd",
        "blockHash": null,
        "blockNumber": null,
        "transactionIndex": null,
        "from": "0xb1cc05ab12928297911695b55ee78c1188f8ef91",
        "to": "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",
        "value": "0xddb66b2addf4800",
        "gas": "0x5622",
        "gasPrice": "0xba43b7400",
        "input": "0x"
    }
}
```

**Comment by tcoulter** [comment]
FYI: These three tests...

https://github.com/MetaMask/provider-engine/blob/master/test/cache.js#L9

Are actually only one test being run three times, because of this line:

https://github.com/MetaMask/provider-engine/blob/master/test/cache.js#L46

Although the payload is different for each call to `cacheTest`, `cacheTest` hardcodes the payload that's sent to `cacheCheck`, making each call to `cacheTest` functionally the same. The tests fail when line 46 is set to pass the correct payload to `cacheCheck`. Working to fix them.

**Comment by kumavis** [comment]
ah shit :hankey: 
nice find
