### ISSUE TITLE
Getting LocalRPC accounts/Wallet Accounts

### ISSUE THREAD

**Issue by Moejoe90** [MetaMask/provider-engine#146]
This is actually more of a question than an issue, 
So when i use the provider engine and add an RPC sub-provider in my case testRPC 
getAccounts returns to me all the ten default public-key available in testRPC 
If i add a hooked-wallet sub-provider
getAccounts only returns the wallets public key and doesn't seem to pass the request to testRPC. 

Is this behavior done on purpose? if so, Whats the reason?

**Comment by flyswatter** [comment]
Hooked Wallet Subprovider is for "hooking in" to signing operations, so that you can pass unsigned transactions to an external signer, and then return them signed.

You can see all of its methods laid out here:
https://github.com/MetaMask/provider-engine/blob/master/zero.js#L40-L59

If you don't define its callbacks, you haven't told it how to sign transactions, and it will have nothing to pass to the TestRPC provider.

If you just want to sign with TestRPC, you don't need to use HookedWalletSubprovider at all.

Does that answer your question?
