### ISSUE TITLE
Supporting synchronous dapps, "Web3ProviderEngine does not support synchronous requests."

### ISSUE THREAD

**Issue by mandelmonkey** [MetaMask/provider-engine#259]
Apologies this is not really an issue but I developed a dapp browser using this repo however when loading some notable dapps (that work with the metamask chrome extension) in my dapp browser I get the error ```Web3ProviderEngine does not support synchronous requests```

I see the dapp is calling synchronous methods and seems like they should be calling async however the dapps works in the metamask chrome extension.

So my question is, is this in issue with the dapp? i.e. they should upgrade to asynchronous request
or is it good practice to support both in a dapp browser? Why does metamask chrome extension work with sync but not this repo?

thanks!

**Comment by jamespic** [comment]
MetaMask adds a wrapper around this library, and one of the things in that wrapper is [an implementation](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/lib/inpage-provider.js#L61) of the synchronous `send` method.

Well-written dapps will not use this method (not least, because they'll fail unit tests using Ganache), but unfortunately not all dapps are well-written. If you want a "MetaMask-compatible" provider, you'll need to provide a `send` method - the version in MetaMask is a good starting point.

**Comment by mandelmonkey** [comment]
ok thanks for the reply, I guess it also needs a wrapper for a sync getaccounts method?

**Comment by kumavis** [comment]
hi @mandelmonkey, i really enjoyed playing with Takara and left a little something in mikura-jima

@jamespic's feedback is correct
